// A simple set of ~10 avatars generated by DiceBear (no image assets to ship).
// Plain seeds = reliable, varied faces. The chosen `uri` is stored on the user.
const BASE = 'https://api.dicebear.com/9.x';
const BG = 'backgroundColor=eaf4ff,c0aede,ffd5dc,d1f7e8,ffe7ba,b6e3f4&radius=50';

const SEEDS = [
  'Aiden', 'Sophia', 'Leo', 'Maya', 'Noah',
  'Ava', 'Ethan', 'Mia', 'Liam', 'Zoe',
];

export const AVATARS = SEEDS.map((seed, i) => ({
  id: `avatar-${i + 1}`,
  uri: `${BASE}/avataaars/png?seed=${seed}&${BG}`,
}));
